import { JobPosition } from './types';

export const JOB_POSITIONS: JobPosition[] = [
  {
    id: 'crew_store',
    title: 'Crew Store',
    department: 'Sari Madu Store',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 0 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'Store',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/crew-store-ah-dac',
  },
  {
    id: 'kasir',
    title: 'Kasir',
    department: 'Sari Madu Store',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 0 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'CreditCard',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/kasir-e8m',
  },
  {
    id: 'waiters',
    title: 'Waiters',
    department: 'Sari Madu Store',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 0 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'UtensilsCrossed',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/crew-soto-dae',
  },
  {
    id: 'koki_produksi',
    title: 'Koki Produksi',
    department: 'Central Kitchen',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 1 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'ChefHat',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/koki-daf',
  },
  {
    id: 'packing',
    title: 'Packing',
    department: 'Central Kitchen',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 0 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'Package',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/packing-d8d',
  },
  {
    id: 'cleaning_service',
    title: 'Cleaning Service',
    department: 'Sari Madu Store',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 0 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'Sparkles',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/cleaning-service-d8w',
  },
  {
    id: 'dishwasher',
    title: 'Dishwasher',
    department: 'Central Kitchen',
    location: 'Samarinda, Kalimantan Timur - On Site',
    type: 'Kontrak',
    experience: 'Min. 0 Tahun',
    education: 'SMA/SMK',
    salaryRange: '-',
    iconName: 'Droplets',
    description: '',
    responsibilities: [],
    requirements: [],
    benefits: [],
    whatsappTemplate: '',
    talentaLink: 'https://recruitment-new.talenta.co/sari-madu-bakery-0/dishwasher-ffi',
  },
];
